<a href="https://colab.research.google.com/github/fredagbona/suiteMl_Tasks/blob/main/Impl%C3%A9mentation_du_produit_matriciel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Problème 1] Calculer manuellement le produit matriciel

In [ ]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#procédure manuelle pour faire le produit matriciel !

#c[0,0] = (a[0] * b[:,0]).sum()
#c[0,1] = (a[0] * b[:,1]).sum()
#c[0,2] = (a[0] * b[:,2]).sum()
#c[1,0] = (a[1] * b[:,0]).sum()
#c[1,1] = (a[1] * b[:,1]).sum()
#c[1,2] = (a[1] * b[:,2]).sum()
#c[2,0] = (a[1] * b[:,0]).sum()
#c[2,1] = (a[1] * b[:,1]).sum()
#c[2,2] = (a[1] * b[:,2]).sum()

c = [[(a[0] * b[:,0]).sum(),(a[0] * b[:,1]).sum(), (a[0] * b[:,2]).sum()],
     [(a[1] * b[:,0]).sum(),(a[1] * b[:,1]).sum(), (a[1] * b[:,2]).sum()],
     [(a[2] * b[:,0]).sum(),(a[2] * b[:,1]).sum(), (a[2] * b[:,2]).sum()]]   

print(np.array(c))

[Problème 2] Calcul par la fonction NumPy

In [1]:
import numpy as np
#import numpy.matlib
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# with matmul
%time print(np.matmul(a,b))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
CPU times: user 2.93 ms, sys: 648 µs, total: 3.58 ms
Wall time: 9.72 ms


In [2]:
# with dot()
%time print(np.dot(a,b))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
CPU times: user 1.45 ms, sys: 0 ns, total: 1.45 ms
Wall time: 1.47 ms


In [3]:
# with @ operator
%time print(a@b)

c = a@b
print(c.sum())

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
CPU times: user 1.99 ms, sys: 0 ns, total: 1.99 ms
Wall time: 3.24 ms
0


[Problème 3] Implémenter le calcul d'un certain élément

In [4]:

import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
elt = 0
for k in range(len(a)): 
    elt += a[0,k] * b[k,0]

print(elt)

6


[Problème 4] Création d'une fonction qui effectue une multiplication matricielle

In [5]:
import numpy as np

a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


def ndarrayProduct(a_ndarray,b_ndarray):
    
    
    elt = 0    
    new_matrix = []

    for k in range(a_ndarray.shape[0]):  
        
        elt_list = [] # list to stock each line mutiliplication
        
        for i in range(a_ndarray.shape[0]):

            elt = 0 #matrix elt

            for j in range(a_ndarray.shape[1]):

                elt += (a_ndarray[k,j] * b_ndarray[j,i]) 
            
            elt_list.append(elt)
            
        new_matrix.append(elt_list)


    return new_matrix


print(ndarrayProduct(a,b))

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


[Problème 5] Juger l'entrée pour laquelle le calcul n'est pas défini

In [ ]:
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])

e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])


def ndarrayProduct(a_ndarray,b_ndarray):
    

    if a_ndarray.shape[1]!= b_ndarray.shape[0]: 
 

        err_msg = "vos deux matrices doivent avoir la même longueur pour être multipliables"

        return err_msg

    elt = 0    
    new_matrix = []
   

    for k in range(a_ndarray.shape[0]):  
        
        elt_list = [] # list to stock each line mutiliplication
        
        for i in range(a_ndarray.shape[0]):

            elt = 0 #matrix elt

            for j in range(a_ndarray.shape[1]):

                elt += (a_ndarray[k,j] * b_ndarray[j,i]) 
            
            elt_list.append(elt)
            
        new_matrix.append(elt_list)


    return new_matrix


print(ndarrayProduct(d_ndarray,e_ndarray))

[Problème 6] Transposition

In [6]:
import numpy as np
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print("using np.transpose()") 
print(ndarrayProduct(d_ndarray,e_ndarray.T))


print("\n")
print("verification using .T") 
print(d_ndarray@e_ndarray.T)

using np.transpose()
[[46, -4], [-34, 73]]


verification using .T
[[ 46  -4]
 [-34  73]]
